"""Requirement-level planning above source selection."""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field, replace
from datetime import date
from enum import Enum

from .models import PlanMode, SourcePlan, SourceType
from .web_source_policy import WebSourcePolicy, parse_web_source_policy
from .source_planner import SourcePlanner, _is_local_compute_query
from .task_decomposition import LightweightTaskDecomposer
from .temporal import TemporalResolution, TemporalResolver
from .tool_necessity import (
    ToolDecisionMode,
    ToolNecessityDecision,
    ToolNecessityPolicy,
)
from .trace import notify_runtime_artifact, record_trace_event


logger = logging.getLogger(__name__)


class TaskStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    SUCCESS = "success"
    INSUFFICIENT = "insufficient"
    SOURCE_FAILURE = "source_failure"
    GENERATION_FAILURE = "generation_failure"
    PROVIDER_CONTENT_BLOCK = "provider_content_block"
    CLARIFICATION_NEEDED = "clarification_needed"


_SUCCESS = TaskStatus.SUCCESS.value


@dataclass
class TaskRequirement:
    """One atomic requirement and its planned primary execution source.

    ``source`` is the planner's primary source assignment.  It is deliberately
    not mutated when execution uses a conditional fallback; actual source usage
    is represented by ``source.execution.*`` trace events.
    """

    id: str
    question: str
    source: str | None
    required: bool = True
    depends_on: list[str] = field(default_factory=list)
    expected_output: str | None = None
    # Optional semantic retrieval query generated by the same LLM call that
    # decomposed the requirement. It is still constrained by the RAG policy.
    retrieval_query: str | None = None
    status: str = TaskStatus.PENDING.value
    evidence_ids: list[str] = field(default_factory=list)
    answer_fragment: str | None = None
    missing_information: list[str] = field(default_factory=list)
    tool_decision: ToolNecessityDecision | None = None
    # This is scoped to the atomic requirement rather than the aggregate
    # TaskPlan.  It authorizes conditional recovery only; Web is not a planned
    # required source when this is true.
    web_fallback_allowed: bool = False
    web_source_policy: WebSourcePolicy = field(default_factory=WebSourcePolicy)
    # Preserve per-requirement scope instead of projecting a union of siblings.
    source_plan: SourcePlan | None = None
    output_evidence: list[dict] = field(default_factory=list)

    def __post_init__(self) -> None:
        if not self.id.strip() or not self.question.strip():
            raise ValueError("task id and question must be non-empty")
        if self.source is not None and self.source not in {
            SourceType.SQL.value,
            SourceType.RAG.value,
            SourceType.WEB.value,
            SourceType.DIRECT.value,
            SourceType.LOCAL_COMPUTE.value,
        }:
            raise ValueError(f"unsupported task source: {self.source}")

    @property
    def successful(self) -> bool:
        return self.status == _SUCCESS

    def start(self) -> None:
        if self.successful:
            return
        self.status = TaskStatus.RUNNING.value

    def complete(self, *, answer: str, evidence_ids: list[str] | tuple[str, ...] = ()) -> None:
        if self.status != TaskStatus.RUNNING.value:
            raise RuntimeError(f"task is not running: {self.id}")
        if not isinstance(answer, str) or not answer.strip():
            raise ValueError("successful task requires a non-empty answer")
        self.status = _SUCCESS
        self.answer_fragment = answer.strip()
        self.evidence_ids = list(dict.fromkeys(evidence_ids))
        self.missing_information = []

    def fail(self, status: str, *, missing_information: list[str] | tuple[str, ...] = ()) -> None:
        normalized = TaskStatus(status)
        if normalized in {TaskStatus.PENDING, TaskStatus.RUNNING, TaskStatus.SUCCESS}:
            raise ValueError(f"not a terminal task failure: {status}")
        self.status = normalized.value
        self.answer_fragment = None
        self.missing_information = [item for item in missing_information if item]

    def to_dict(self) -> dict[str, object]:
        return {
            "id": self.id,
            "question": self.question,
            "source": self.source,
            "required": self.required,
            "depends_on": list(self.depends_on),
            "expected_output": self.expected_output,
            "retrieval_query": self.retrieval_query,
            "status": self.status,
            "evidence_ids": list(self.evidence_ids),
            "answer_fragment": self.answer_fragment,
            "missing_information": list(self.missing_information),
            "tool_decision": self.tool_decision.to_dict() if self.tool_decision else None,
            "web_fallback_allowed": self.web_fallback_allowed,
            "web_source_policy": self.web_source_policy.to_dict(),
            "source_plan": self.source_plan.to_dict() if self.source_plan else None,
        }


@dataclass
class TaskPlan:
    original_question: str
    resolved_question: str
    source_plan: SourcePlan
    tasks: list[TaskRequirement]
    reference_date: date
    temporal_resolution: TemporalResolution

    def __post_init__(self) -> None:
        if not self.tasks:
            raise ValueError("TaskPlan requires at least one task")
        identifiers = [task.id for task in self.tasks]
        if len(set(identifiers)) != len(identifiers):
            raise ValueError("TaskPlan task ids must be unique")
        known = set(identifiers)
        for task in self.tasks:
            if not set(task.depends_on).issubset(known):
                raise ValueError(f"task {task.id} has unknown dependencies")
            if task.id in task.depends_on:
                raise ValueError(f"task {task.id} cannot depend on itself")
        pending = {task.id: set(task.depends_on) for task in self.tasks}
        while pending:
            ready = {identifier for identifier, dependencies in pending.items() if not dependencies}
            if not ready:
                raise ValueError("TaskPlan dependencies contain a cycle")
            pending = {identifier: dependencies - ready for identifier, dependencies in pending.items()
                       if identifier not in ready}

    @property
    def required_tasks(self) -> tuple[TaskRequirement, ...]:
        return tuple(task for task in self.tasks if task.required)

    @property
    def execution_tasks(self) -> tuple[TaskRequirement, ...]:
        return tuple(task for task in self.tasks if task.source is not None)

    @property
    def synthesis_tasks(self) -> tuple[TaskRequirement, ...]:
        return tuple(task for task in self.tasks if task.source is None)

    @property
    def all_required_successful(self) -> bool:
        return all(task.successful for task in self.required_tasks)

    @property
    def any_required_successful(self) -> bool:
        return any(task.successful for task in self.required_tasks)

    @property
    def completion_status(self) -> str:
        if self.all_required_successful:
            return TaskStatus.SUCCESS.value
        if self.any_required_successful:
            return "partial_success"
        statuses = {task.status for task in self.required_tasks}
        if statuses.issubset({TaskStatus.PENDING.value, TaskStatus.RUNNING.value}):
            return TaskStatus.PENDING.value
        for status in (
            TaskStatus.CLARIFICATION_NEEDED.value,
            TaskStatus.PROVIDER_CONTENT_BLOCK.value,
            TaskStatus.GENERATION_FAILURE.value,
            TaskStatus.INSUFFICIENT.value,
            TaskStatus.SOURCE_FAILURE.value,
        ):
            if status in statuses:
                return status
        return TaskStatus.SOURCE_FAILURE.value

    def dependencies_satisfied(self, task: TaskRequirement) -> bool:
        by_id = {candidate.id: candidate for candidate in self.tasks}
        return all(by_id[dependency].successful for dependency in task.depends_on)

    def task_for_source(self, source: str) -> TaskRequirement | None:
        return next((task for task in self.execution_tasks if task.source == source), None)

    def to_dict(self) -> dict[str, object]:
        return {
            "original_question": self.original_question,
            "resolved_question": self.resolved_question,
            "reference_date": self.reference_date.isoformat(),
            "source_plan": self.source_plan.to_dict(),
            "temporal_resolution": self.temporal_resolution.to_dict(),
            "tasks": [task.to_dict() for task in self.tasks],
            "all_required_successful": self.all_required_successful,
            "completion_status": self.completion_status,
        }


class TaskPlanner:
    """Decompose requirements before deciding necessity and selecting sources."""

    def __init__(
        self,
        source_planner: SourcePlanner,
        *,
        temporal_resolver: TemporalResolver | None = None,
        reference_date: date | None = None,
        task_decomposer: LightweightTaskDecomposer | None = None,
        necessity_policy: ToolNecessityPolicy | None = None,
    ) -> None:
        self.source_planner = source_planner
        self.temporal_resolver = temporal_resolver or TemporalResolver(reference_date)
        self.reference_date = reference_date
        if (task_decomposer is None) != (necessity_policy is None):
            raise ValueError("task_decomposer and necessity_policy must be configured together")
        self.task_decomposer = task_decomposer
        self.necessity_policy = necessity_policy

    @property
    def uses_tool_necessity(self) -> bool:
        return self.task_decomposer is not None and self.necessity_policy is not None

    def plan(self, question: str, source_plan: SourcePlan | None = None) -> TaskPlan:
        recommendation_gaps = _investment_recommendation_gaps(question)
        if recommendation_gaps:
            temporal = self.temporal_resolver.resolve(question, reference_date=self.reference_date)
            plan = SourcePlan(
                mode=PlanMode.SINGLE_SOURCE,
                primary_source=SourceType.DIRECT,
                required_sources=(SourceType.DIRECT,),
                web_fallback_allowed=False,
                web_source_policy=parse_web_source_policy(question),
                routing_method="deterministic_clarification_guard",
                reason="an investment recommendation lacks required decision inputs",
            )
            task = TaskRequirement(
                id="T1",
                question=question,
                source=SourceType.DIRECT.value,
                expected_output="补充作出适当性判断所需的信息",
                status=TaskStatus.CLARIFICATION_NEEDED.value,
                missing_information=recommendation_gaps,
            )
            return self._finish(question, question, plan, temporal, [task])
        # A request explicitly limited to the local database is an atomic SQL
        # contract.  Splitting its requested output columns creates sibling
        # queries that can lose shared time/entity predicates; DirectSQL's
        # semantic compiler and result evaluator already operate on the whole
        # contract.
        request_policy = parse_web_source_policy(question)
        if (
            self.uses_tool_necessity
            and source_plan is None
            and not request_policy.web_permitted
            and "数据库" in question
        ):
            return self.plan(question, source_plan=self.source_planner.plan(question))
        if self.uses_tool_necessity and source_plan is None:
            return self._plan_by_requirement(question)

        temporal = self.temporal_resolver.resolve(question, reference_date=self.reference_date)
        resolved = temporal.resolved_text
        plan = source_plan or self.source_planner.plan(resolved)
        # Keep the simple (non-decomposed) path equivalent to the
        # requirement-level path: explicit source constraints are a property
        # of the request, not an incidental property of a router decision.
        request_web_policy = parse_web_source_policy(question)
        plan = replace(
            plan,
            web_fallback_allowed=plan.web_fallback_allowed and request_web_policy.web_permitted,
            web_source_policy=request_web_policy,
        )
        # "Only use the local database" is stronger than document-type words
        # such as "annual report" inside the requested database row.  Do not
        # turn a structured holding lookup into an unnecessary RAG sibling.
        if not request_web_policy.web_permitted and "数据库" in question:
            plan = replace(
                plan,
                mode=PlanMode.SINGLE_SOURCE,
                primary_source=SourceType.SQL,
                required_sources=(SourceType.SQL,),
                web_fallback_allowed=False,
                routing_method="explicit_local_database_constraint",
                reason="user explicitly restricted this request to the local database",
            )

        if temporal.clarification_needed:
            task = TaskRequirement(
                id="T1",
                question=resolved,
                source=plan.primary_source.value if plan.primary_source else None,
                expected_output="明确的时间锚点",
                status=TaskStatus.CLARIFICATION_NEEDED.value,
                missing_information=[temporal.clarification_question or "时间锚点不明确"],
            )
            return self._finish(question, resolved, plan, temporal, [task])

        if not request_web_policy.web_permitted and "数据库" in question and plan.primary_source is SourceType.SQL:
            task = TaskRequirement(
                id="T1",
                question=resolved,
                source=SourceType.SQL.value,
                expected_output=_expected_output(SourceType.SQL.value),
                web_fallback_allowed=False,
                web_source_policy=request_web_policy,
                source_plan=plan,
            )
            return self._finish(question, resolved, plan, temporal, [task])

        compound_sql = self._compound_sql_tasks(resolved, plan)
        if compound_sql:
            return self._finish(question, resolved, plan, temporal, compound_sql)

        if plan.mode is PlanMode.MULTI_SOURCE:
            tasks = self._hybrid_tasks(resolved, plan)
            return self._finish(question, resolved, plan, temporal, tasks)

        source = plan.primary_source.value if plan.primary_source else None
        task = TaskRequirement(
            id="T1",
            question=resolved,
            source=source,
            expected_output=_expected_output(source),
            web_fallback_allowed=plan.web_fallback_allowed,
            web_source_policy=plan.web_source_policy,
        )
        return self._finish(question, resolved, plan, temporal, [task])

    def _plan_by_requirement(
        self,
        original: str,
    ) -> TaskPlan:
        assert self.task_decomposer is not None and self.necessity_policy is not None
        # Parse once from the parent request: a decomposed child often no longer
        # contains wording such as "only use the CSRC official site".
        request_web_policy = parse_web_source_policy(original)
        # Requirement boundaries must be established before relative time is
        # normalized.  Otherwise an unresolved compound reaches one executor.
        decomposed = self.task_decomposer.decompose(original)
        # Lookup scaffolding ("what is the full text", "where can it be found")
        # is retrieval work, not a user requirement.  When the request never
        # asked for it, such a child replaces the enumerated asks and makes the
        # plan unanswerable.
        decomposed = _drop_invented_lookup_requirements(original, decomposed)
        temporal_by_id = {
            item.id: self.temporal_resolver.resolve(
                item.question,
                reference_date=self.reference_date,
            )
            for item in decomposed
        }
        resolved_requirements = tuple(
            replace(item, question=temporal_by_id[item.id].resolved_text)
            for item in decomposed
        )
        temporal = self.temporal_resolver.resolve(original, reference_date=self.reference_date)
        resolved = temporal.resolved_text
        clarification = next(
            (
                temporal_by_id[item.id]
                for item in decomposed
                if item.required and temporal_by_id[item.id].clarification_needed
            ),
            None,
        )
        logger.debug(
            "TASK_DECOMPOSITION: %s",
            json.dumps(
                {
                    "requirements": [item.to_dict() for item in decomposed],
                    "temporally_resolved_requirements": [
                        item.to_dict() for item in resolved_requirements
                    ],
                },
                ensure_ascii=False,
            ),
        )
        _record_decomposition(resolved_requirements)

        if clarification is not None:
            entity = self.source_planner.resolver.resolve(resolved)
            plan = SourcePlan(
                mode=PlanMode.AUTO,
                primary_source=None,
                required_sources=(),
                company_name=entity.company_name,
                catalog_doc_ids=((entity.catalog_doc_id,) if entity.catalog_doc_id else ()),
                document_type=entity.document_type,
                web_fallback_allowed=False,
                routing_method="tool_necessity_policy",
                reason="temporal clarification required before execution",
            )
            tasks = [
                TaskRequirement(
                    id=item.id,
                    question=item.question,
                    source=None,
                    required=item.required,
                    depends_on=list(item.depends_on),
                    expected_output=item.expected_output or "明确的时间锚点",
                    status=(
                        TaskStatus.CLARIFICATION_NEEDED.value
                        if temporal_by_id[item.id].clarification_needed
                        else TaskStatus.PENDING.value
                    ),
                    missing_information=(
                        [temporal_by_id[item.id].clarification_question or "时间锚点不明确"]
                        if temporal_by_id[item.id].clarification_needed
                        else []
                    ),
                )
                for item in resolved_requirements
            ]
            return self._finish(
                original,
                resolved,
                plan,
                temporal,
                tasks,
                trace_requirements=resolved_requirements,
                trace_decomposition=False,
            )

        decisions_by_id: dict[str, ToolNecessityDecision] = {}
        undecided_requirements = []
        for item in resolved_requirements:
            if _is_local_compute_query(item.question) or _is_local_compute_query(original):
                decisions_by_id[item.id] = ToolNecessityDecision(
                    task_id=item.id,
                    mode=ToolDecisionMode.NO_TOOL,
                    reason="deterministic local computation inputs are fully present",
                    information_gap=None,
                    external_evidence_required=False,
                    freshness_required=False,
                    decision_method="deterministic_local_compute_guard",
                )
                continue
            deterministic_sources = self.source_planner.deterministic_external_sources(
                item.question
            )
            if deterministic_sources:
                catalog_bound_rag = (
                    deterministic_sources == (SourceType.RAG,)
                    and self.source_planner.catalog_document_source(item.question)
                    is SourceType.RAG
                )
                decisions_by_id[item.id] = ToolNecessityDecision(
                    task_id=item.id,
                    mode=ToolDecisionMode.TOOL_REQUIRED,
                    reason=(
                        "catalogued company question requires scoped local document evidence"
                        if catalog_bound_rag
                        else "deterministic source constraints require external evidence"
                    ),
                    information_gap="external source evidence is required",
                    external_evidence_required=True,
                    freshness_required=SourceType.WEB in deterministic_sources,
                    specified_sources=deterministic_sources,
                    required_capabilities=(
                        ("catalog_document_evidence",)
                        if catalog_bound_rag
                        else tuple(
                            f"{source.value}_source_evidence"
                            for source in deterministic_sources
                        )
                    ),
                    decision_method=(
                        "deterministic_catalog_constraint"
                        if catalog_bound_rag
                        else "deterministic_hard_constraint"
                    ),
                )
            else:
                undecided_requirements.append(item)
        if undecided_requirements:
            decisions_by_id.update(
                (decision.task_id, decision)
                for decision in self.necessity_policy.decide(
                    undecided_requirements,
                    reference_date=temporal.reference_date,
                )
            )
        for item in resolved_requirements:
            decision = decisions_by_id[item.id]
            guarded_sources = self.source_planner.guarded_external_sources(item.question)
            if decision.mode is ToolDecisionMode.NO_TOOL and guarded_sources:
                decisions_by_id[item.id] = ToolNecessityDecision(
                    task_id=item.id,
                    mode=ToolDecisionMode.TOOL_REQUIRED,
                    reason="no-tool decision contradicted deterministic source capability constraints",
                    information_gap="external source evidence is required",
                    external_evidence_required=True,
                    freshness_required=SourceType.WEB in guarded_sources,
                    specified_sources=guarded_sources,
                    required_capabilities=tuple(
                        f"{source.value}_source_evidence" for source in guarded_sources
                    ),
                    optional_capabilities=decision.optional_capabilities,
                    decision_method="deterministic_route_guard_correction",
                )
        decisions = tuple(decisions_by_id[item.id] for item in resolved_requirements)
        for decision in decisions:
            record_trace_event(
                event_type="planning.tool_necessity.decided",
                stage="planning",
                status="completed",
                task_id=decision.task_id,
                attributes={
                    "mode": decision.mode.value,
                    "decision_method": decision.decision_method,
                    "external_evidence_required": decision.external_evidence_required,
                    "freshness_required": decision.freshness_required,
                    "required_capabilities": list(decision.required_capabilities),
                    "specified_sources": [
                        source.value for source in decision.specified_sources
                    ],
                },
            )
        decision_by_id = {decision.task_id: decision for decision in decisions}

        # A finite literal calculation is one atomic computation even when the
        # decomposer separated output fields.  Keeping separate children loses
        # shared operands and makes the synthesis layer re-interpret numbers.
        if (
            len(resolved_requirements) > 1
            and all(decision.mode is ToolDecisionMode.NO_TOOL for decision in decisions)
            and _is_local_compute_query(original)
        ):
            first = resolved_requirements[0]
            resolved_requirements = (replace(first, question=original, depends_on=()),)
            decision_by_id = {first.id: decision_by_id[first.id]}
        else:
            # A paired metric (growth rate, difference, ratio) is computed from
            # two endpoints and cannot be split per endpoint.  Decomposers
            # sometimes emit "growth rate of the first day" and "growth rate of
            # the last day", which leaves neither child answerable.
            paired_clause = _paired_metric_clause(original, resolved_requirements)
            if paired_clause is not None:
                paired_positions = [
                    position
                    for position, item in enumerate(resolved_requirements)
                    if any(marker in item.question for marker in _PAIRED_METRIC_MARKERS)
                ]
                first = resolved_requirements[paired_positions[0]]
                merged = replace(first, question=paired_clause, depends_on=())
                remaining = tuple(
                    item
                    for position, item in enumerate(resolved_requirements)
                    if position not in paired_positions
                )
                resolved_requirements = (merged, *remaining)
                decision_by_id = {
                    item.id: decision_by_id[item.id]
                    for item in resolved_requirements
                }

        tasks: list[TaskRequirement] = []
        selected_plans: list[SourcePlan] = []
        generated_ids: dict[str, list[str]] = {}
        for item in resolved_requirements:
            decision = decision_by_id[item.id]
            item_web_policy = parse_web_source_policy(item.question)
            effective_web_policy = (
                item_web_policy
                if item_web_policy.mode.value != "open"
                else request_web_policy
            )
            # A dependent SQL clause may mention a date discovered by its Web
            # sibling.  Its explicit local-only boundary still governs how the
            # clause itself is executed; the dependency supplies data, not a
            # second permission to browse.
            if (
                _explicit_local_database_only(item.question)
                and SourceType.SQL in decision.specified_sources
                and SourceType.WEB in decision.specified_sources
            ):
                decision = replace(
                    decision,
                    specified_sources=(SourceType.SQL,),
                    freshness_required=False,
                    required_capabilities=tuple(
                        capability
                        for capability in decision.required_capabilities
                        if capability != "fresh_or_specified_web_information"
                    ),
                    decision_method=decision.decision_method + "+clause_source_boundary",
                )
                decision_by_id[item.id] = decision
            if decision.mode is ToolDecisionMode.EXPLORATORY:
                raise RuntimeError(f"legacy exploration required for task {item.id}: {decision.reason}")
            if decision.mode is ToolDecisionMode.NO_TOOL:
                # The necessity decision has already authorized a no-tool
                # answer.  Do not re-enter ambiguous source routing here: it
                # can turn a valid no-tool task into an unnecessary Web call.
                no_tool_source = (
                    SourceType.LOCAL_COMPUTE
                    if _is_local_compute_query(item.question)
                    else SourceType.DIRECT
                )
                no_tool_plan = SourcePlan(
                    mode=PlanMode.SINGLE_SOURCE,
                    primary_source=no_tool_source,
                    required_sources=(no_tool_source,),
                    web_fallback_allowed=False,
                    web_source_policy=effective_web_policy,
                    routing_method="tool_necessity_no_tool",
                    reason="tool necessity policy authorized a no-tool task",
                )
                tasks.append(
                    TaskRequirement(
                        id=item.id,
                        # A calculation decomposer may split requested outputs
                        # (for example final amount vs cumulative return) while
                        # placing the numeric inputs in only one child.  Local
                        # computation is safe only with the complete literal
                        # input context, so retain the parent wording here.
                        question=(original if no_tool_source is SourceType.LOCAL_COMPUTE else item.question),
                        source=no_tool_source.value,
                        required=item.required,
                        depends_on=list(item.depends_on),
                        expected_output=item.expected_output or _expected_output(no_tool_source.value),
                        retrieval_query=item.retrieval_query,
                        tool_decision=decision,
                        web_source_policy=effective_web_policy,
                        source_plan=no_tool_plan,
                    )
                )
                selected_plans.append(no_tool_plan)
                generated_ids[item.id] = [item.id]
                continue

            selection = self.source_planner.select_external(item.question, decision)
            selection = replace(
                selection,
                web_fallback_allowed=(
                    selection.web_fallback_allowed and effective_web_policy.web_permitted
                ),
                web_source_policy=effective_web_policy,
            )
            if not selection.required_sources or selection.primary_source is None:
                raise RuntimeError(f"external source selection unresolved for task {item.id}")
            selected_plans.append(selection)
            for source in selection.required_sources:
                task_id = item.id if len(selection.required_sources) == 1 else f"{item.id}_{source.value}"
                tasks.append(
                    TaskRequirement(
                        id=task_id,
                        question=item.question,
                        source=source.value,
                        required=item.required,
                        depends_on=list(item.depends_on),
                        expected_output=item.expected_output or _expected_output(source.value),
                        retrieval_query=item.retrieval_query,
                        tool_decision=decision,
                        web_fallback_allowed=selection.web_fallback_allowed,
                        web_source_policy=effective_web_policy,
                        source_plan=selection,
                    )
                )
                generated_ids.setdefault(item.id, []).append(task_id)

        # An alternative assertion ("A 或 B 是否成立") is one evidence
        # obligation. Splitting it into independent RAG generations can make
        # every child reject an intentionally partial phrase even when one
        # passage directly settles the whole assertion.
        if _should_collapse_rag_alternatives(original, tasks):
            first = tasks[0]
            first.question = original
            first.retrieval_query = original
            first.depends_on = []
            tasks = [first]
            generated_ids = {first.tool_decision.task_id: [first.id]}
            resolved_requirements = (replace(
                resolved_requirements[0],
                question=original,
                retrieval_query=original,
                depends_on=(),
            ),)

        decomposed_by_id = {item.id: item for item in resolved_requirements}
        for task in tasks:
            assert task.tool_decision is not None
            original_requirement = decomposed_by_id[task.tool_decision.task_id]
            task.depends_on = [
                generated_id
                for dependency in original_requirement.depends_on
                for generated_id in generated_ids[dependency]
            ]

        sources = tuple(
            dict.fromkeys(SourceType(task.source) for task in tasks if task.source is not None)
        )
        entity = self.source_planner.resolver.resolve(resolved)
        company_name = next((plan.company_name for plan in selected_plans if plan.company_name), entity.company_name)
        catalog_doc_ids = tuple(
            dict.fromkeys(doc_id for plan in selected_plans for doc_id in plan.catalog_doc_ids)
        )
        document_type = next((plan.document_type for plan in selected_plans if plan.document_type), entity.document_type)
        mode = PlanMode.MULTI_SOURCE if len(sources) > 1 else PlanMode.SINGLE_SOURCE
        plan = SourcePlan(
            mode=mode,
            primary_source=sources[0],
            required_sources=sources,
            company_name=company_name,
            catalog_doc_ids=catalog_doc_ids,
            document_type=document_type,
            web_fallback_allowed=any(plan.web_fallback_allowed for plan in selected_plans),
            web_source_policy=request_web_policy,
            routing_method="task_decomposition+tool_necessity+source_selection",
            reason="minimum required execution mode selected independently for each TaskRequirement",
        )
        if len(tasks) > 1:
            tasks.append(
                TaskRequirement(
                    id="SYNTHESIS",
                    question=resolved,
                    source=None,
                    required=True,
                    depends_on=[task.id for task in tasks if task.required],
                    expected_output="综合所有已完成的 required TaskRequirement",
                )
            )
        return self._finish(
            original,
            resolved,
            plan,
            temporal,
            tasks,
            trace_requirements=resolved_requirements,
            trace_decomposition=False,
        )

    def _finish(
        self,
        original: str,
        resolved: str,
        plan: SourcePlan,
        temporal: TemporalResolution,
        tasks: list[TaskRequirement],
        trace_requirements=None,
        trace_decomposition: bool = True,
    ) -> TaskPlan:
        task_plan = TaskPlan(
            original_question=original,
            resolved_question=resolved,
            source_plan=plan,
            tasks=tasks,
            reference_date=temporal.reference_date,
            temporal_resolution=temporal,
        )
        if trace_decomposition:
            requirements = tuple(
                trace_requirements
                or task_plan.execution_tasks
                or task_plan.required_tasks
            )
            _record_decomposition(requirements)
        logger.debug("TASK_PLAN: %s", json.dumps(task_plan.to_dict(), ensure_ascii=False))
        notify_runtime_artifact("task_plan.planned", task_plan)
        return task_plan
    @staticmethod
    def _compound_sql_tasks(resolved: str, plan: SourcePlan) -> list[TaskRequirement]:
        if not (
            plan.mode is PlanMode.SINGLE_SOURCE
            and plan.required_sources == (SourceType.SQL,)
        ):
            return []
        clauses = [item.strip(" ，,\n") for item in re.split(r"[？?；;。]+", resolved) if item.strip(" ，,\n")]
        if len(clauses) < 2:
            return []
        first = clauses[0]
        first_year = re.search(r"((?:19|20)\d{2})年", first)
        if first_year is None:
            return []
        inherited = re.sub(r"^(?:19|20)\d{2}年", "", first).strip()
        inherited = re.sub(r"(?:是谁|是哪些|有哪些)$", "是谁", inherited)
        tasks: list[TaskRequirement] = []
        for index, clause in enumerate(clauses, start=1):
            task_question = clause
            year = re.search(r"((?:19|20)\d{2})年", clause)
            elliptical = bool(re.fullmatch(r"(?:19|20)\d{2}年(?:又)?(?:是)?(?:哪些|谁|多少)", clause))
            if index > 1 and year is not None and elliptical:
                task_question = f"{year.group(1)}年{inherited}"
            tasks.append(
                TaskRequirement(
                    id=f"T{index}",
                    question=task_question + ("？" if not task_question.endswith("？") else ""),
                    source=SourceType.SQL.value,
                    expected_output=f"独立回答第 {index} 个 SQL 时间片要求",
                )
            )
        return tasks

    @staticmethod
    def _hybrid_tasks(resolved: str, plan: SourcePlan) -> list[TaskRequirement]:
        tasks: list[TaskRequirement] = []
        for index, source in enumerate(plan.required_sources, start=1):
            tasks.append(
                TaskRequirement(
                    id=f"T{index}",
                    question=_hybrid_source_question(resolved, plan, source),
                    source=source.value,
                    expected_output=_expected_output(source.value),
                )
            )
        dependencies = [task.id for task in tasks]
        tasks.append(
            TaskRequirement(
                id=f"T{len(tasks) + 1}",
                question=resolved,
                source=None,
                depends_on=dependencies,
                expected_output="综合所有 required source task，并逐 claim 引用证据",
            )
        )
        return tasks


def _investment_recommendation_gaps(question: str) -> list[str]:
    if not any(marker in question for marker in ("值得买", "是否值得购买", "能买吗", "是否适合购买")):
        return []
    if not any(marker in question for marker in ("某基金", "一只基金", "这个基金", "该基金")):
        return []
    return [
        "请提供具体基金名称或代码",
        "请说明要评价的表现期限或比较基准",
        "请补充风险承受能力、投资目标和预计持有期限",
    ]


def _should_collapse_rag_alternatives(question: str, tasks: list[TaskRequirement]) -> bool:
    return (
        len(tasks) > 1
        and "或" in question
        and any(marker in question for marker in ("是否", "能否", "能不能", "可否"))
        and all(task.source == SourceType.RAG.value and not task.depends_on for task in tasks)
    )


_PAIRED_METRIC_MARKERS = ("增长率", "差额", "差值", "增幅", "涨幅", "比值", "倍数", "之差", "相差")
_LOOKUP_SCAFFOLDING_MARKERS = ("全文", "全称", "在哪里", "哪里可以", "全文是什么")


def _drop_invented_lookup_requirements(original: str, requirements):
    """Remove retrieval-scaffolding children the request never asked for."""

    if len(requirements) <= 1:
        return requirements
    kept = tuple(
        item
        for item in requirements
        if not (
            any(marker in item.question for marker in _LOOKUP_SCAFFOLDING_MARKERS)
            and not any(marker in original for marker in _LOOKUP_SCAFFOLDING_MARKERS)
        )
    )
    return kept or requirements
_PAIRED_FIRST_MARKERS = ("首", "第一个", "第一", "期初", "最初")
_PAIRED_LAST_MARKERS = ("末", "最后一个", "最后", "期末", "最终", "结束")


def _paired_metric_clause(original: str, requirements) -> str | None:
    """Return the source clause of a paired metric that must stay atomic."""

    if len(requirements) < 2:
        return None
    if not any(marker in original for marker in _PAIRED_METRIC_MARKERS):
        return None
    children = [
        item.question
        for item in requirements
        if any(marker in item.question for marker in _PAIRED_METRIC_MARKERS)
    ]
    # A decomposer may place the metric only in the parent request and split
    # children into “first endpoint” and “last endpoint”.  Those children are
    # still one atomic calculation; otherwise a dialogue follow-up can return
    # two values while silently dropping its requested formula and rate.
    if len(children) < 2:
        children = [
            item.question
            for item in requirements
            if any(marker in item.question for marker in _PAIRED_FIRST_MARKERS + _PAIRED_LAST_MARKERS)
        ]
    if len(children) < 2:
        return None
    if not any(any(marker in text for marker in _PAIRED_FIRST_MARKERS) for text in children):
        return None
    if not any(any(marker in text for marker in _PAIRED_LAST_MARKERS) for text in children):
        return None
    for clause in re.split(r"[；;。\n]", original):
        clause = clause.strip()
        if not clause:
            continue
        if any(marker in clause for marker in _PAIRED_METRIC_MARKERS) and any(
            marker in clause for marker in ("本地数据库", "数据库", "数据表", "行情表")
        ):
            return clause
    return None


def _explicit_local_database_only(question: str) -> bool:
    return bool(re.search(r"(?:只|仅|仅限|只能|限于).{0,16}(?:本地数据库|数据库|sql)", question, re.I))


def _record_decomposition(requirements) -> None:
    record_trace_event(
        event_type="planning.task_decomposition.completed",
        stage="planning",
        status="completed",
        attributes={
            "requirement_count": len(requirements),
            "required_requirement_count": sum(
                1 for requirement in requirements if requirement.required
            ),
            "requirement_ids": [requirement.id for requirement in requirements],
            "dependency_count": sum(
                len(requirement.depends_on) for requirement in requirements
            ),
        },
    )


def _expected_output(source: str | None) -> str:
    return {
        SourceType.SQL.value: "结构化数据库结果及 SQL provenance",
        SourceType.RAG.value: "限定本地文档范围内的证据与回答片段",
        SourceType.WEB.value: "当前公开 Web 证据与回答片段",
        SourceType.DIRECT.value: "稳定、无需外部来源的直接回答",
        SourceType.LOCAL_COMPUTE.value: "本地确定性计算结果",
    }.get(source, "回答当前原子要求")


def _hybrid_source_question(question: str, plan: SourcePlan, source: SourceType) -> str:
    company = plan.company_name or "目标实体"
    if source is SourceType.RAG:
        instruction = f"仅回答{company}本地{plan.document_type or '金融文档'}中与原问题有关的历史披露部分。"
    elif source is SourceType.SQL:
        instruction = "仅回答原问题中可由本地结构化金融数据库验证的指标、行情或持仓部分。"
    else:
        instruction = "仅回答原问题中需要当前或近期公开 Web 信息支持的部分。"
    return f"{question.strip()}\n\n原子任务边界：{instruction}"
